# Generated by Django 5.0.4 on 2024-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='elias123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
