# Generated by Django 5.0.4 on 2024-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
