# Generated by Django 5.0.4 on 2024-05-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='2000', max_digits=15),
            preserve_default=False,
        ),
    ]
